package com.nextgen.store.admin;
import com.nextgen.store.catalog.*; import com.nextgen.store.order.*; import com.nextgen.store.review.*; import org.springframework.data.domain.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.math.*; import java.util.*;
@RestController @RequestMapping("/api/v1/admin") @PreAuthorize("hasRole('ADMIN')") @Transactional
public class AdminController {
 private final ProductRepository products; private final ProductVariantRepository variants; private final CategoryRepository categories; private final OrderRepository orders; private final ReviewRepository reviews;
 public AdminController(ProductRepository products,ProductVariantRepository variants,CategoryRepository categories,OrderRepository orders,ReviewRepository reviews){this.products=products;this.variants=variants;this.categories=categories;this.orders=orders;this.reviews=reviews;}
 @GetMapping("/products") public Page<ProductSummary> products(Pageable p){return products.findAll(p).map(x->new ProductSummary(x.getId(),x.getName(),x.getSlug(),x.getDescription(),x.getPrice(),x.getRating(),x.getImageUrl(),x.isActive(),x.getCategory().getId(),x.getCategory().getName()));}
 @PostMapping("/products") public ProductSummary createProduct(@RequestBody ProductRequest r){return view(products.save(new Product(req(r.name()),req(r.slug()),req(r.description()),money(r.price()),rating(r.rating()),req(r.imageUrl()),category(r.categoryId()))));}
 @PutMapping("/products/{id}") public ProductSummary updateProduct(@PathVariable Long id,@RequestBody ProductRequest r){Product x=product(id);x.setName(req(r.name()));x.setSlug(req(r.slug()));x.setDescription(req(r.description()));x.setPrice(money(r.price()));x.setImageUrl(req(r.imageUrl()));x.setCategory(category(r.categoryId()));if(r.rating()!=null)x.setRating(rating(r.rating()));if(r.active()!=null)x.setActive(r.active());return view(x);}
 @DeleteMapping("/products/{id}") public void archiveProduct(@PathVariable Long id){product(id).setActive(false);}
 @GetMapping("/products/{id}/variants") public List<VariantSummary> variants(@PathVariable Long id){product(id);return variants.findByProductIdOrderBySizeAscColorAsc(id).stream().map(this::variant).toList();}
 @PostMapping("/products/{id}/variants") public VariantSummary createVariant(@PathVariable Long id,@RequestBody VariantRequest r){return variant(variants.save(new ProductVariant(product(id),req(r.sku()),req(r.size()),req(r.color()),stock(r.stockQuantity()),r.priceOverride())));}
 @PutMapping("/variants/{id}") public VariantSummary updateVariant(@PathVariable Long id,@RequestBody VariantRequest r){ProductVariant x=variants.findById(id).orElseThrow(()->new NoSuchElementException("Variant not found"));x.setSku(req(r.sku()));x.setSize(req(r.size()));x.setColor(req(r.color()));x.setStockQuantity(stock(r.stockQuantity()));x.setPriceOverride(r.priceOverride());if(r.active()!=null)x.setActive(r.active());return variant(x);}
 @DeleteMapping("/variants/{id}") public void archiveVariant(@PathVariable Long id){variants.findById(id).orElseThrow(()->new NoSuchElementException("Variant not found")).setActive(false);}
 @GetMapping("/orders") public Page<OrderSummary> orderList(Pageable p){return orders.findAll(p).map(x->new OrderSummary(x.getId(),x.getStatus().name(),x.getPaymentMethod(),x.getPaymentStatus(),x.getTotalAmount(),x.getCreatedAt()));}
 @PatchMapping("/orders/{id}/status") public OrderSummary orderStatus(@PathVariable Long id,@RequestBody StatusRequest r){Order x=orders.findById(id).orElseThrow(()->new NoSuchElementException("Order not found"));OrderStatus n;try{n=OrderStatus.valueOf(req(r.status()).toUpperCase());}catch(IllegalArgumentException e){throw new IllegalArgumentException("Invalid order status");}if(!allowed(x.getStatus(),n))throw new IllegalArgumentException("Invalid order status transition");if(n==OrderStatus.CANCELLED&&!x.isStockReleased()){x.getItems().forEach(i->i.getVariant().increaseStock(i.getQuantity()));x.markStockReleased();}x.setStatus(n);return new OrderSummary(x.getId(),x.getStatus().name(),x.getPaymentMethod(),x.getPaymentStatus(),x.getTotalAmount(),x.getCreatedAt());}
 @GetMapping("/reviews") public Page<ReviewSummary> reviewList(Pageable p){return reviews.findAll(p).map(x->new ReviewSummary(x.getId(),x.getProduct().getId(),x.getProduct().getName(),x.getRating(),x.getTitle(),x.getBody(),x.getStatus().name(),x.getCreatedAt()));}
 @PatchMapping("/reviews/{id}/status") public ReviewSummary reviewStatus(@PathVariable Long id,@RequestBody StatusRequest r){Review x=reviews.findById(id).orElseThrow(()->new NoSuchElementException("Review not found"));try{x.setStatus(ReviewStatus.valueOf(req(r.status()).toUpperCase()));}catch(IllegalArgumentException e){throw new IllegalArgumentException("Invalid review status");}refresh(x.getProduct());return new ReviewSummary(x.getId(),x.getProduct().getId(),x.getProduct().getName(),x.getRating(),x.getTitle(),x.getBody(),x.getStatus().name(),x.getCreatedAt());}
 private void refresh(Product p){p.setRating(BigDecimal.valueOf(reviews.averageRating(p.getId())).setScale(2,RoundingMode.HALF_UP));} private boolean allowed(OrderStatus a,OrderStatus b){return switch(a){case PENDING_PAYMENT->b==OrderStatus.CONFIRMED||b==OrderStatus.CANCELLED;case CONFIRMED->b==OrderStatus.PROCESSING||b==OrderStatus.CANCELLED;case PROCESSING->b==OrderStatus.SHIPPED;case SHIPPED->b==OrderStatus.DELIVERED;case DELIVERED,CANCELLED->false;};}
 private Product product(Long id){return products.findById(id).orElseThrow(()->new NoSuchElementException("Product not found"));} private Category category(Long id){return categories.findById(id).orElseThrow(()->new NoSuchElementException("Category not found"));} private String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Required field missing");return v.trim();} private BigDecimal money(BigDecimal v){if(v==null||v.signum()<0)throw new IllegalArgumentException("Invalid price");return v.setScale(2,RoundingMode.HALF_UP);} private BigDecimal rating(BigDecimal v){if(v==null||v.signum()<0||v.compareTo(BigDecimal.valueOf(5))>0)throw new IllegalArgumentException("Invalid rating");return v.setScale(2,RoundingMode.HALF_UP);} private int stock(int v){if(v<0)throw new IllegalArgumentException("Invalid stock");return v;} private ProductSummary view(Product x){return new ProductSummary(x.getId(),x.getName(),x.getSlug(),x.getDescription(),x.getPrice(),x.getRating(),x.getImageUrl(),x.isActive(),x.getCategory().getId(),x.getCategory().getName());} private VariantSummary variant(ProductVariant x){return new VariantSummary(x.getId(),x.getSku(),x.getSize(),x.getColor(),x.getStockQuantity(),x.getPriceOverride(),x.getProduct().getPrice(),x.isActive());}
 public record ProductRequest(String name,String slug,String description,BigDecimal price,BigDecimal rating,String imageUrl,Long categoryId,Boolean active){} public record VariantRequest(String sku,String size,String color,int stockQuantity,BigDecimal priceOverride,Boolean active){} public record StatusRequest(String status){} public record ProductSummary(Long id,String name,String slug,String description,BigDecimal price,BigDecimal rating,String imageUrl,boolean active,Long categoryId,String category){} public record VariantSummary(Long id,String sku,String size,String color,int stockQuantity,BigDecimal priceOverride,BigDecimal productPrice,boolean active){} public record OrderSummary(Long id,String status,String paymentMethod,String paymentStatus,BigDecimal totalAmount,java.time.OffsetDateTime createdAt){} public record ReviewSummary(Long id,Long productId,String productName,int rating,String title,String body,String status,java.time.OffsetDateTime createdAt){}
}
