package com.nextgen.store.admin;

import com.nextgen.store.catalog.*; import com.nextgen.store.order.*; import com.nextgen.store.review.*; import org.springframework.data.domain.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.math.*; import java.util.*;
@RestController @RequestMapping("/api/v1/admin") @PreAuthorize("hasRole('ADMIN')") @Transactional
public class AdminController {
 private final ProductRepository products; private final ProductVariantRepository variants; private final CategoryRepository categories; private final OrderRepository orders; private final ReviewRepository reviews;
 public AdminController(ProductRepository products,ProductVariantRepository variants,CategoryRepository categories,OrderRepository orders,ReviewRepository reviews){this.products=products;this.variants=variants;this.categories=categories;this.orders=orders;this.reviews=reviews;}
 @GetMapping("/products") public Page<ProductSummary> products(Pageable pageable){return products.findAll(pageable).map(p->new ProductSummary(p.getId(),p.getName(),p.getSlug(),p.getDescription(),p.getPrice(),p.getRating(),p.getImageUrl(),p.isActive(),p.getCategory().getId(),p.getCategory().getName()));}
 @PostMapping("/products") public ProductSummary createProduct(@RequestBody ProductRequest r){return productView(products.save(new Product(req(r.name()),req(r.slug()),req(r.description()),money(r.price()),rating(r.rating()),req(r.imageUrl()),category(r.categoryId()))));}
 @PutMapping("/products/{id}") public ProductSummary updateProduct(@PathVariable Long id,@RequestBody ProductRequest r){Product p=product(id);p.setName(req(r.name()));p.setSlug(req(r.slug()));p.setDescription(req(r.description()));p.setPrice(money(r.price()));p.setImageUrl(req(r.imageUrl()));p.setCategory(category(r.categoryId()));if(r.rating()!=null)p.setRating(rating(r.rating()));if(r.active()!=null)p.setActive(r.active());return productView(p);}
 @DeleteMapping("/products/{id}") public void archiveProduct(@PathVariable Long id){product(id).setActive(false);}
 @GetMapping("/products/{id}/variants") public List<VariantSummary> variants(@PathVariable Long id){product(id);return variants.findByProductIdOrderBySizeAscColorAsc(id).stream().map(this::variantView).toList();}
 @PostMapping("/products/{id}/variants") public VariantSummary createVariant(@PathVariable Long id,@RequestBody VariantRequest r){return variantView(variants.save(new ProductVariant(product(id),req(r.sku()),req(r.size()),req(r.color()),stock(r.stockQuantity()),r.priceOverride())));}
 @PutMapping("/variants/{id}") public VariantSummary updateVariant(@PathVariable Long id,@RequestBody VariantRequest r){ProductVariant v=variants.findById(id).orElseThrow(()->new NoSuchElementException("Variant not found"));v.setSku(req(r.sku()));v.setSize(req(r.size()));v.setColor(req(r.color()));v.setStockQuantity(stock(r.stockQuantity()));v.setPriceOverride(r.priceOverride());if(r.active()!=null)v.setActive(r.active());return variantView(v);}
 @DeleteMapping("/variants/{id}") public void archiveVariant(@PathVariable Long id){variants.findById(id).orElseThrow(()->new NoSuchElementException("Variant not found")).setActive(false);}
 @GetMapping("/orders") public Page<OrderSummary> orderList(Pageable pageable){return orders.findAll(pageable).map(o->new OrderSummary(o.getId(),o.getStatus().name(),o.getPaymentMethod(),o.getPaymentStatus(),o.getTotalAmount(),o.getCreatedAt()));}
 @PatchMapping("/orders/{id}/status") public OrderSummary orderStatus(@PathVariable Long id,@RequestBody StatusRequest r){Order o=orders.findById(id).orElseThrow(()->new NoSuchElementException("Order not found"));OrderStatus next=OrderStatus.valueOf(req(r.status()).toUpperCase());if(!allowed(o.getStatus(),next))throw new IllegalArgumentException("Invalid order status transition");if(next==OrderStatus.CANCELLED&&!o.isStockReleased()){for(OrderItem i:o.getItems()){} o.markStockReleased();}o.setStatus(next);return new OrderSummary(o.getId(),o.getStatus().name(),o.getPaymentMethod(),o.getPaymentStatus(),o.getTotalAmount(),o.getCreatedAt());}
 @GetMapping("/reviews") public Page<ReviewSummary> reviewList(Pageable pageable){return reviews.findAll(pageable).map(r->new ReviewSummary(r.getId(),r.getProduct().getId(),r.getProduct().getName(),r.getRating(),r.getTitle(),r.getBody(),r.getStatus().name(),r.getCreatedAt()));}
 @PatchMapping("/reviews/{id}/status") public ReviewSummary reviewStatus(@PathVariable Long id,@RequestBody StatusRequest r){Review review=reviews.findById(id).orElseThrow(()->new NoSuchElementException("Review not found"));review.setStatus(ReviewStatus.valueOf(req(r.status()).toUpperCase()));refreshRating(review.getProduct());return new ReviewSummary(review.getId(),review.getProduct().getId(),review.getProduct().getName(),review.getRating(),review.getTitle(),review.getBody(),review.getStatus().name(),review.getCreatedAt());}
 private void refreshRating(Product p){p.setRating(BigDecimal.valueOf(reviews.averageRating(p.getId())).setScale(2,RoundingMode.HALF_UP));}
 private boolean allowed(OrderStatus a,OrderStatus b){return switch(a){case PENDING_PAYMENT->b==OrderStatus.CONFIRMED||b==OrderStatus.CANCELLED;case CONFIRMED->b==OrderStatus.PROCESSING||b==OrderStatus.CANCELLED;case PROCESSING->b==OrderStatus.SHIPPED;case SHIPPED->b==OrderStatus.DELIVERED;case DELIVERED,CANCELLED->false;};}
 private Product product(Long id){return products.findById(id).orElseThrow(()->new NoSuchElementException("Product not found"));} private Category category(Long id){return categories.findById(id).orElseThrow(()->new NoSuchElementException("Category not found"));} private String req(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Required field missing");return v.trim();} private BigDecimal money(BigDecimal v){if(v==null||v.signum()<0)throw new IllegalArgumentException("Invalid price");return v.setScale(2,RoundingMode.HALF_UP);} private BigDecimal rating(BigDecimal v){if(v==null||v.compareTo(BigDecimal.ZERO)<0||v.compareTo(BigDecimal.valueOf(5))>0)throw new IllegalArgumentException("Invalid rating");return v.setScale(2,RoundingMode.HALF_UP);} private int stock(int v){if(v<0)throw new IllegalArgumentException("Invalid stock");return v;}
 private ProductSummary productView(Product p){return new ProductSummary(p.getId(),p.getName(),p.getSlug(),p.getDescription(),p.getPrice(),p.getRating(),p.getImageUrl(),p.isActive(),p.getCategory().getId(),p.getCategory().getName());} private VariantSummary variantView(ProductVariant v){return new VariantSummary(v.getId(),v.getSku(),v.getSize(),v.getColor(),v.getStockQuantity(),v.getPriceOverride(),v.getProduct().getPrice(),v.isActive());}
 public record ProductRequest(String name,String slug,String description,BigDecimal price,BigDecimal rating,String imageUrl,Long categoryId,Boolean active){} public record VariantRequest(String sku,String size,String color,int stockQuantity,BigDecimal priceOverride,Boolean active){} public record StatusRequest(String status){}
 public record ProductSummary(Long id,String name,String slug,String description,BigDecimal price,BigDecimal rating,String imageUrl,boolean active,Long categoryId,String category){} public record VariantSummary(Long id,String sku,String size,String color,int stockQuantity,BigDecimal priceOverride,BigDecimal productPrice,boolean active){} public record OrderSummary(Long id,String status,String paymentMethod,String paymentStatus,BigDecimal totalAmount,java.time.OffsetDateTime createdAt){} public record ReviewSummary(Long id,Long productId,String productName,int rating,String title,String body,String status,java.time.OffsetDateTime createdAt){}
}
