package com.nextgen.store.review;
import com.nextgen.store.auth.*; import com.nextgen.store.catalog.*; import jakarta.validation.*; import jakarta.validation.constraints.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.OffsetDateTime; import java.util.*;
@RestController @RequestMapping("/api/v1/products/{productId}/reviews") public class ReviewController {
 private final ReviewRepository reviews; private final ProductRepository products; private final UserRepository users;
 public ReviewController(ReviewRepository reviews,ProductRepository products,UserRepository users){this.reviews=reviews;this.products=products;this.users=users;}
 @GetMapping public Page<ReviewResponse> list(@PathVariable Long productId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size){if(!products.existsById(productId))throw new NoSuchElementException("Product not found");return reviews.findByProductIdAndStatusOrderByCreatedAtDesc(productId,ReviewStatus.APPROVED,PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),50))).map(ReviewResponse::from);}
 @GetMapping("/summary") public ReviewSummary summary(@PathVariable Long productId){if(!products.existsById(productId))throw new NoSuchElementException("Product not found");return new ReviewSummary(reviews.averageRating(productId),reviews.countByProductIdAndStatus(productId,ReviewStatus.APPROVED));}
 @PostMapping @Transactional public ResponseEntity<?> create(@PathVariable Long productId,Authentication a,@Valid @RequestBody CreateReview r){Product p=products.findById(productId).orElseThrow(()->new NoSuchElementException("Product not found"));User u=users.findByEmailIgnoreCase(a.getName()).orElseThrow(()->new NoSuchElementException("User not found"));if(reviews.findByProductIdAndUserId(productId,u.getId()).isPresent())return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("message","You have already reviewed this product."));Review x=new Review(p,u,r.rating(),clean(r.title()),clean(r.body()));x.setStatus(ReviewStatus.PENDING);reviews.save(x);return ResponseEntity.status(HttpStatus.CREATED).body(ReviewResponse.from(x));}
 private String clean(String v){if(v==null)return null;v=v.trim();return v.isEmpty()?null:v;} public record CreateReview(@Min(1) @Max(5) int rating,@Size(max=160) String title,@Size(max=2000) String body){} public record ReviewResponse(Long id,int rating,String title,String body,String author,OffsetDateTime createdAt){static ReviewResponse from(Review r){return new ReviewResponse(r.getId(),r.getRating(),r.getTitle(),r.getBody(),"GenZ customer",r.getCreatedAt());}} public record ReviewSummary(double averageRating,long reviewCount){}
}
