import { FormEvent, useEffect, useMemo, useState } from 'react';

type CartProduct={id:number;name:string;price:number;imageUrl:string;variantId?:number;size?:string;color?:string;quantity:number};
type Address={id:number;fullName:string;phone:string;line1:string;line2?:string;city:string;state:string;postalCode:string;country:string;defaultAddress:boolean};
type Order={id:number;status:string;subtotal:number;shippingAmount:number;deliveryCharge:number;totalAmount:number;paymentMethod:string;paymentStatus:string;currency:string};
const API=import.meta.env.VITE_API_URL||'http://localhost:8080';
const money=(n:number)=>`₹${Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const authHeaders=()=>({Authorization:`Bearer ${localStorage.getItem('genz_store_token')||''}`,'Content-Type':'application/json'});

export default function Checkout({cart,onDone}:{cart:CartProduct[];onDone:(order?:Order)=>void}){
 const [addresses,setAddresses]=useState<Address[]>([]),[selected,setSelected]=useState<number|null>(null),[showForm,setShowForm]=useState(false),[method,setMethod]=useState<'COD'|'ONLINE'>('COD'),[loading,setLoading]=useState(true),[placing,setPlacing]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({fullName:'',phone:'',line1:'',line2:'',city:'',state:'',postalCode:'',country:'India',defaultAddress:true});
 const subtotal=useMemo(()=>cart.reduce((s,p)=>s+p.price*p.quantity,0),[cart]);
 const delivery=subtotal>=999?0:99; const total=subtotal+delivery;
 useEffect(()=>{fetch(`${API}/api/v1/addresses`,{headers:authHeaders()}).then(r=>r.ok?r.json():Promise.reject(new Error('Unable to load addresses'))).then((data:Address[])=>{setAddresses(data);setSelected(data.find(a=>a.defaultAddress)?.id??data[0]?.id??null)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function addAddress(e:FormEvent){e.preventDefault();setError('');try{const r=await fetch(`${API}/api/v1/addresses`,{method:'POST',headers:authHeaders(),body:JSON.stringify(form)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Could not save address');setAddresses(v=>[data,...v.filter(a=>a.id!==data.id)]);setSelected(data.id);setShowForm(false)}catch(e){setError(e instanceof Error?e.message:'Could not save address')}}
 async function placeOrder(){setError('');if(!selected){setError('Please select a delivery address.');return}if(!cart.length){setError('Your bag is empty.');return}if(cart.some(p=>!p.variantId)){setError('Please select size and color for every item.');return}setPlacing(true);try{const r=await fetch(`${API}/api/v1/orders`,{method:'POST',headers:authHeaders(),body:JSON.stringify({addressId:selected,paymentMethod:method,items:cart.map(p=>({variantId:p.variantId,quantity:p.quantity}))})});const order=await r.json().catch(()=>({}));if(!r.ok)throw new Error(order.message||'Could not create order');if(method==='COD'){const pr=await fetch(`${API}/api/v1/payments/cod`,{method:'POST',headers:authHeaders(),body:JSON.stringify({orderId:order.id})});const payment=await pr.json().catch(()=>({}));if(!pr.ok)throw new Error(payment.message||'Could not confirm COD payment');onDone(order);return}
 const cr=await fetch(`${API}/api/v1/payments/razorpay/create-order`,{method:'POST',headers:authHeaders(),body:JSON.stringify({orderId:order.id})});const created=await cr.json().catch(()=>({}));if(!cr.ok)throw new Error(created.message||'Razorpay is not configured');
 await new Promise<void>((resolve,reject)=>{const finish=()=>{const Razorpay=(window as any).Razorpay;if(!Razorpay){reject(new Error('Razorpay Checkout could not load.'));return}const rz=new Razorpay({key:created.keyId,amount:Math.round(Number(created.amount)*100),currency:created.currency,name:'GenZ Store',description:'GenZ Store order',order_id:created.razorpayOrderId,handler:async(response:any)=>{try{const vr=await fetch(`${API}/api/v1/payments/razorpay/verify`,{method:'POST',headers:authHeaders(),body:JSON.stringify({orderId:order.id,razorpayOrderId:response.razorpay_order_id,razorpayPaymentId:response.razorpay_payment_id,razorpaySignature:response.razorpay_signature})});const vd=await vr.json().catch(()=>({}));if(!vr.ok)throw new Error(vd.message||'Payment verification failed');resolve()}catch(e){reject(e)}} ,modal:{ondismiss:()=>reject(new Error('Payment was cancelled.'))}});rz.open()};if((window as any).Razorpay){finish();return}const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=finish;script.onerror=()=>reject(new Error('Could not load Razorpay Checkout.'));document.body.appendChild(script)});onDone(order);
 }catch(e){setError(e instanceof Error?e.message:'Checkout failed')}finally{setPlacing(false)}}
 if(loading)return <section className="checkoutPage"><h1>Checkout</h1><p>Loading your saved addresses…</p></section>;
 return <section className="checkoutPage"><div className="checkoutHead"><button onClick={()=>onDone()}>← Back to bag</button><div><span>GENZ STORE</span><h1>Secure checkout</h1></div></div><div className="checkoutGrid"><div className="checkoutMain"><div className="checkoutCard"><div className="cardTitle"><h2>1. Delivery address</h2><button onClick={()=>setShowForm(v=>!v)}>{showForm?'Close':'＋ Add address'}</button></div>{addresses.length===0&&!showForm&&<p>No saved address yet. Add one to continue.</p>}{addresses.map(a=><button key={a.id} className={`addressOption ${selected===a.id?'selected':''}`} onClick={()=>setSelected(a.id)}><strong>{a.fullName} {a.defaultAddress&&<small>DEFAULT</small>}</strong><span>{a.phone}</span><span>{a.line1}{a.line2?`, ${a.line2}`:''}</span><span>{a.city}, {a.state} — {a.postalCode}, {a.country}</span></button>)}{showForm&&<form className="addressForm" onSubmit={addAddress}>{Object.entries(form).filter(([k])=>k!=='defaultAddress').map(([k,v])=><input key={k} required={!['line2'].includes(k)} placeholder={k.replace(/([A-Z])/g,' $1')} value={String(v)} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/>) }<label><input type="checkbox" checked={form.defaultAddress} onChange={e=>setForm(x=>({...x,defaultAddress:e.target.checked}))}/> Make this my default address</label><button type="submit">Save address</button></form>}</div><div className="checkoutCard"><div className="cardTitle"><h2>2. Payment method</h2></div><button className={`paymentOption ${method==='COD'?'selected':''}`} onClick={()=>setMethod('COD')}><strong>Cash on Delivery</strong><span>Pay when your order arrives. Delivery charge is calculated above.</span></button><button className={`paymentOption ${method==='ONLINE'?'selected':''}`} onClick={()=>setMethod('ONLINE')}><strong>Razorpay — UPI / Cards / Netbanking</strong><span>Secure online payment.</span></button></div>{error&&<div className="checkoutError">{error}</div>}<button className="placeOrder" disabled={placing||!selected||!cart.length} onClick={placeOrder}>{placing?'Processing…':`Place order · ${money(total)}`}</button></div><aside className="checkoutSummary"><h2>Order summary</h2>{cart.map(p=><div className="summaryItem" key={`${p.id}-${p.variantId}`}><img src={p.imageUrl} alt=""/><div><strong>{p.name}</strong><span>{p.size} · {p.color} · Qty {p.quantity}</span></div><b>{money(p.price*p.quantity)}</b></div>)}<hr/><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery</span><b>{delivery===0?'FREE':money(delivery)}</b></div><div className="total"><span>Total</span><b>{money(total)}</b></div><small>All prices are calculated from the server at order creation.</small></aside></div></section>;
}
