import { FormEvent, useEffect, useState } from 'react';
import { LogIn, Send, Star } from 'lucide-react';
import './ReviewSection.css';

type Review={id:number;rating:number;title?:string|null;body?:string|null;author:string;createdAt:string};
type Summary={averageRating:number;reviewCount:number};
const api=import.meta.env.VITE_API_URL||'http://localhost:8080';

export default function ReviewSection({productId}:{productId:number}){
 const [reviews,setReviews]=useState<Review[]>([]),[summary,setSummary]=useState<Summary>({averageRating:0,reviewCount:0}),[rating,setRating]=useState(0),[title,setTitle]=useState(''),[body,setBody]=useState(''),[loading,setLoading]=useState(true),[posting,setPosting]=useState(false),[notice,setNotice]=useState('');
 const token=localStorage.getItem('genz_store_token')||localStorage.getItem('nextgen_token');
 const load=()=>{setLoading(true);Promise.all([fetch(`${api}/api/v1/products/${productId}/reviews`).then(r=>r.ok?r.json():Promise.reject()),fetch(`${api}/api/v1/products/${productId}/reviews/summary`).then(r=>r.ok?r.json():Promise.reject())]).then(([r,s])=>{setReviews(r.content||[]);setSummary(s)}).catch(()=>setNotice('Reviews are unavailable right now.')).finally(()=>setLoading(false))};
 useEffect(load,[productId]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!token){setNotice('Please sign in to write a review.');return}if(!rating){setNotice('Choose a rating first.');return}setPosting(true);setNotice('');fetch(`${api}/api/v1/products/${productId}/reviews`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({rating,title,body})}).then(async r=>{if(r.status===409)throw new Error('You have already reviewed this product.');if(!r.ok)throw new Error('Could not publish your review.');return r.json()}).then(()=>{setRating(0);setTitle('');setBody('');setNotice('Thanks — your review is live.');load()}).catch(e=>setNotice(e.message)).finally(()=>setPosting(false))};
 return <section className="reviewSection"><div className="reviewHead"><div><span className="micro">COMMUNITY FEEDBACK</span><h2>Reviews</h2><p>Real thoughts from the GenZ Store community.</p></div><div className="reviewScore"><strong>{summary.averageRating.toFixed(1)}</strong><span>{[1,2,3,4,5].map(i=><Star key={i} size={13} fill={i<=Math.round(summary.averageRating)?'currentColor':'none'}/>)}</span><small>{summary.reviewCount} {summary.reviewCount===1?'review':'reviews'}</small></div></div>
 <div className="reviewGrid"><div className="reviewList">{loading?<p className="reviewMuted">Loading reviews…</p>:reviews.length===0?<p className="reviewMuted">No reviews yet. Be the first to share your experience.</p>:reviews.map(r=><article className="reviewCard" key={r.id}><div className="reviewCardTop"><div className="reviewStars">{[1,2,3,4,5].map(i=><Star key={i} size={12} fill={i<=r.rating?'currentColor':'none'}/>)}</div><time>{new Date(r.createdAt).toLocaleDateString('en-IN')}</time></div><h3>{r.title||'GenZ Store review'}</h3>{r.body&&<p>{r.body}</p>}<span>{r.author}</span></article>)}</div>
 <form className="reviewForm" onSubmit={submit}><div className="formTitle"><strong>Share your experience</strong><span>{token?'Verified account review':'Sign in to review'}</span></div>{!token&&<div className="reviewSignIn"><LogIn/><span>Sign in to leave a review. Your review helps other shoppers.</span></div>}<label>Rating<div className="ratingPicker">{[1,2,3,4,5].map(i=><button type="button" key={i} aria-label={`${i} stars`} onClick={()=>setRating(i)}><Star size={19} fill={i<=rating?'currentColor':'none'}/></button>)}</div></label><label>Title<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What stood out?"/></label><label>Review<textarea maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Tell the community about fit, quality and feel…"/></label><button className="reviewSubmit" disabled={posting}>{posting?'Publishing…':<>Publish review <Send/></>}</button>{notice&&<p className="reviewNotice">{notice}</p>}</form></div></section>;
}
