import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ChevronRight, Heart, Menu, Search, ShoppingBag, Sparkles, UserCircle, X, SlidersHorizontal, Trash2, Minus, Plus, Truck, RotateCcw, ShieldCheck, Headphones, Send, Star } from 'lucide-react';
import AuthModal from './components/AuthModal';

type Product={id:number;name:string;slug:string;description:string;price:number;rating:number;category:string;imageUrl:string};
type Msg={role:'user'|'assistant';text:string;products?:Product[]};
const cats=['T-Shirts','Hoodies','Jeans & Pants','Jackets','Sneakers','Caps & Hats','Bags','Sunglasses','Watches','Jewellery','Accessories'];
const fallback:Product[]=[
{id:1,name:'Oversized Graphic Tee',slug:'oversized-graphic-tee',description:'Relaxed streetwear fit.',price:799,rating:4.8,category:'T-Shirts',imageUrl:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=85'},
{id:2,name:'Street Classic Sneakers',slug:'street-classic-sneakers',description:'Everyday street sneakers.',price:2499,rating:4.7,category:'Sneakers',imageUrl:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85'},
{id:3,name:'Baggy Cargo Jeans',slug:'baggy-cargo-jeans',description:'Loose utility cargo silhouette.',price:1899,rating:4.6,category:'Jeans & Pants',imageUrl:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=85'},
{id:4,name:'Minimal Hoodie',slug:'minimal-hoodie',description:'Clean heavyweight hoodie.',price:1699,rating:4.8,category:'Hoodies',imageUrl:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=85'},
{id:5,name:'NY Baseball Cap',slug:'ny-baseball-cap',description:'Classic everyday cap.',price:599,rating:4.5,category:'Caps & Hats',imageUrl:'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=85'},
{id:6,name:'Aero Sunglasses',slug:'aero-sunglasses',description:'Minimal statement frames.',price:999,rating:4.6,category:'Sunglasses',imageUrl:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=85'}];
const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;

export default function App(){
 const [products,setProducts]=useState(fallback),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[liked,setLiked]=useState<number[]>([]),[cart,setCart]=useState<Product[]>([]),[cartOpen,setCartOpen]=useState(false),[chatOpen,setChatOpen]=useState(false),[authOpen,setAuthOpen]=useState(false),[user,setUser]=useState<{firstName:string;email:string}|null>(null),[chatInput,setChatInput]=useState('');
 const [messages,setMessages]=useState<Msg[]>([{role:'assistant',text:'Tell me the occasion, your style and budget. I will build a look from the GenZ Store catalog.'}]);
 useEffect(()=>{fetch(`${import.meta.env.VITE_API_URL||'http://localhost:8080'}/api/v1/products`).then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>{});const u=localStorage.getItem('genz_store_user')||localStorage.getItem('nextgen_user');if(u)try{setUser(JSON.parse(u))}catch{};try{setLiked(JSON.parse(localStorage.getItem('genz_store_wishlist')||'[]'));setCart(JSON.parse(localStorage.getItem('genz_store_cart')||'[]'))}catch{}},[]);
 useEffect(()=>localStorage.setItem('genz_store_wishlist',JSON.stringify(liked)),[liked]);useEffect(()=>localStorage.setItem('genz_store_cart',JSON.stringify(cart)),[cart]);
 const visible=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(!query||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(query.toLowerCase()))),[products,category,query]);
 const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const ai=(text:string):Msg=>{const s=text.toLowerCase();let pool=[...products];const m=s.match(/(?:under|below|within)\s*₹?\s*(\d[\d,]*)/);if(m)pool=pool.filter(p=>p.price<=Number(m[1].replace(/,/g,'')));if(s.includes('hoodie'))pool=pool.filter(p=>p.category==='Hoodies');else if(s.includes('sneaker')||s.includes('shoe'))pool=pool.filter(p=>p.category==='Sneakers');else if(s.includes('cargo')||s.includes('jean')||s.includes('pant'))pool=pool.filter(p=>p.category==='Jeans & Pants');else if(s.includes('tee')||s.includes('t-shirt'))pool=pool.filter(p=>p.category==='T-Shirts');pool.sort((a,b)=>b.rating-a.rating);pool=pool.slice(0,3);return pool.length?{role:'assistant',text:`Based on your request, I recommend ${pool.map(p=>`${p.name} (${money(p.price)})`).join(', ')}. These are the strongest matches in the current catalog.`,products:pool}:{role:'assistant',text:'I could not find an exact match in the current catalog. Try another category or a higher budget.'}};
 const send=(text=chatInput)=>{const s=text.trim();if(!s)return;setMessages(v=>[...v,{role:'user',text:s},ai(s)]);setChatInput('')};
 const add=(p:Product)=>{setCart(v=>v.some(x=>x.id===p.id)?v:[...v,p]);setCartOpen(true)};
 const logout=()=>{localStorage.removeItem('genz_store_token');localStorage.removeItem('genz_store_user');setUser(null)};
 return <main>
  <div className="topbar"><span>Free shipping on orders above ₹999</span><i/><span>New season arrivals</span><i/><span>Easy 7-day returns</span><label>Track Order&nbsp;&nbsp; | &nbsp;&nbsp;Help</label></div>
  <header className="siteHeader"><button className="mobileMenu"><Menu/></button><button className="brand" onClick={()=>go('home')}>GenZ<span>Store</span><small>WEAR YOUR STORY</small></button><nav>{[['Home','home'],['Shop','shop'],['Collections','collections'],['New In','newin'],['Brands','brands'],['Sale','sale'],['AI Stylist','ai']].map(([t,id])=><button key={id} onClick={()=>go(id)}>{t}</button>)}</nav><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go('shop')} placeholder="Search for products, brands, styles..."/><kbd>/</kbd></div><button className="headerIcon" onClick={()=>go('wishlist')}><Heart fill={liked.length?'currentColor':'none'}/>{liked.length>0&&<b>{liked.length}</b>}</button><button className="headerIcon" onClick={()=>setCartOpen(true)}><ShoppingBag/>{cart.length>0&&<b>{cart.length}</b>}</button>{user?<button className="accountButton" onClick={logout} title="Sign out of PROJEXA SOLUTIONS"><UserCircle/><small>PROJEXA SOLUTIONS</small></button>:<button className="headerIcon" onClick={()=>setAuthOpen(true)}><UserCircle/></button>}</header>
  <section className="hero" id="home"><div className="heroLead"><span className="micro">NEW SEASON / 2024</span><h1>More than<br/>just <em>fashion.</em></h1><p>Curated streetwear, everyday essentials and accessories for a generation that dresses with intent.</p><div className="heroActions"><button className="primary" onClick={()=>go('shop')}>Shop the collection <ArrowRight/></button><button className="secondary" onClick={()=>setChatOpen(true)}><Sparkles/> Try AI Stylist</button></div><div className="heroStats"><div><strong>50K+</strong><span>Customers</span></div><div><strong>4.8/5</strong><span>Average rating</span></div><div><strong>100%</strong><span>Secure payments</span></div></div></div><div className="heroVisual"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1300&q=90" alt="GenZ streetwear"/><div className="visualNote">CLOTHES<br/>CULTURE<br/>PEOPLE</div><div className="visualCount">01 / 03</div></div><aside className="aiCard" id="ai"><div className="aiTop"><span><Sparkles/> AI STYLIST</span><small>PRIVATE BETA</small></div><h2>Style recommendations<br/>that feel personal.</h2><p>Build complete outfits using your vibe, occasion and budget.</p><div className="aiPrompts"><button onClick={()=>{setChatOpen(true);send('Suggest a college outfit under ₹2000')}}>College outfit under ₹2000 <ChevronRight/></button><button onClick={()=>{setChatOpen(true);send('What goes with my black cargos?')}}>Style my black cargos <ChevronRight/></button><button onClick={()=>{setChatOpen(true);send('Show me trending streetwear')}}>Trending streetwear <ChevronRight/></button></div><button className="aiCTA" onClick={()=>setChatOpen(true)}>Open AI Stylist <ArrowRight/></button></aside></section>
  <section className="categoryRail" id="collections">{cats.map((c,i)=><button key={c} onClick={()=>{setCategory(c);go('shop')}}><div className="catImage"><img src={fallback[i%fallback.length].imageUrl} alt=""/></div><span>{c}</span></button>)}<button onClick={()=>{setCategory('All');go('shop')}}><div className="catArrow"><ArrowRight/></div><span>View All</span></button></section>
  <section className="featureGrid" id="newin"><article className="feature darkFeature"><div><span className="micro">NEW SEASON</span><h2>New energy.<br/>New essentials.</h2><p>Fresh silhouettes made for everyday rotation.</p><button onClick={()=>go('shop')}>Explore arrivals <ArrowRight/></button></div><img src={fallback[3].imageUrl} alt="New season"/></article><article className="feature dealFeature" id="sale"><span className="micro">LIMITED EDIT</span><h2>Up to<br/><strong>50% off</strong></h2><p>Selected styles, limited quantities.</p><button onClick={()=>go('shop')}>Shop sale <ArrowRight/></button></article><article className="feature communityFeature"><span className="micro">GENZ COMMUNITY</span><h2>Real people.<br/>Real style.</h2><p>Discover how the community wears it.</p><button onClick={()=>go('community')}>Meet the crew <ArrowRight/></button></article></section>
  <section className="productsSection" id="shop"><div className="sectionHead"><div><span className="micro">CURATED FOR YOU</span><h2>Trending right now</h2><p>Most loved styles from the current catalog.</p></div><button onClick={()=>{setCategory('All');setQuery('')}}>View all <ArrowRight/></button></div><div className="filterRow"><div>{['All','T-Shirts','Hoodies','Jeans & Pants','Sneakers','Accessories'].map(c=><button className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><button className="filterButton"><SlidersHorizontal/> Filters</button></div><div className="productGrid">{visible.map(p=><article className="productCard" key={p.id}><div className="productImage"><img src={p.imageUrl} alt={p.name}/><button onClick={()=>setLiked(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/></button><button className="quickAdd" onClick={()=>add(p)}>Add to bag</button></div><div className="productInfo"><div><h3>{p.name}</h3><span>{p.category}</span></div><strong>{money(p.price)}</strong><div className="rating"><Star size={12} fill="currentColor"/> {p.rating}</div></div></article>)}</div></section>
  <section className="lookBanner"><div><span className="micro">THE GENZ EDIT</span><h2>Build a wardrobe<br/>that feels like you.</h2><p>Use AI Stylist for combinations, occasions and budgets — without leaving the store.</p><button onClick={()=>setChatOpen(true)}>Build my look <ArrowRight/></button></div><div className="lookTiles"><img src={fallback[1].imageUrl} alt="Sneakers"/><img src={fallback[4].imageUrl} alt="Cap"/><img src={fallback[5].imageUrl} alt="Sunglasses"/></div></section>
  <section className="community" id="community"><div><span className="micro">GENZ CREW</span><h2>Style is better<br/>when it is shared.</h2><p>Join a community discovering new fits, drops and everyday inspiration.</p><button onClick={()=>go('home')}>Join the community <ArrowRight/></button></div><div className="communityImages"><img src={fallback[0].imageUrl} alt="Community style"/><img src={fallback[3].imageUrl} alt="Community style"/><img src={fallback[2].imageUrl} alt="Community style"/></div></section>
  <section className="benefits"><div><Truck/><strong>Free Shipping</strong><span>Orders above ₹999</span></div><div><RotateCcw/><strong>Easy Returns</strong><span>7-day hassle free</span></div><div><ShieldCheck/><strong>Secure Payments</strong><span>Protected checkout</span></div><div><Headphones/><strong>24/7 Support</strong><span>We're always here</span></div></section>
  <footer><div className="footerBrand"><button className="brand" onClick={()=>go('home')}>GenZ<span>Store</span><small>WEAR YOUR STORY</small></button><p>A product by <strong>PROJEXA SOLUTIONS</strong></p></div><div className="footerLinks"><div><strong>Shop</strong><button onClick={()=>go('shop')}>All Products</button><button onClick={()=>go('newin')}>New Arrivals</button><button onClick={()=>go('sale')}>Sale</button></div><div><strong>Company</strong><button>About</button><button>Careers</button><button>Contact</button></div><div><strong>Help</strong><button>Shipping</button><button>Returns</button><button>Privacy</button></div></div><div className="footerBottom"><span>© 2026 GenZ Store. All rights reserved.</span><span>Good outfits. Better days.</span></div></footer>
  {chatOpen&&<div className="drawerOverlay" onClick={()=>setChatOpen(false)}><section className="aiDrawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><span className="micro">GENZ STORE AI</span><h2>AI Stylist</h2></div><button onClick={()=>setChatOpen(false)}><X/></button></div><div className="chatBody">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div>{m.text}</div>{m.products&&<div className="aiProducts">{m.products.map(p=><button key={p.id} onClick={()=>add(p)}><img src={p.imageUrl} alt=""/><span>{p.name}<small>{money(p.price)}</small></span><Plus/></button>)}</div>}</div>)}</div><div className="drawerQuick"><button onClick={()=>send('Suggest a college outfit under ₹2000')}>College under ₹2000</button><button onClick={()=>send('Show me sneakers under ₹3000')}>Sneakers under ₹3000</button><button onClick={()=>send('Show me trending streetwear')}>Trending streetwear</button></div><form className="aiInput" onSubmit={e=>{e.preventDefault();send()}}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Describe your style, occasion or budget..."/><button><Send/></button></form></section></div>}
  {cartOpen&&<div className="drawerOverlay" onClick={()=>setCartOpen(false)}><aside className="cartDrawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><span className="micro">YOUR BAG</span><h2>Shopping bag</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="emptyState"><ShoppingBag/><p>Your bag is empty.</p><button onClick={()=>{setCartOpen(false);go('shop')}}>Continue shopping</button></div>:<><div className="cartItems">{cart.map(p=><div className="cartItem" key={p.id}><img src={p.imageUrl} alt={p.name}/><div><strong>{p.name}</strong><span>{money(p.price)}</span><button onClick={()=>setCart(v=>v.filter(x=>x.id!==p.id))}><Trash2/> Remove</button></div><div className="qty"><button><Minus/></button><span>1</span><button><Plus/></button></div></div>)}</div><div className="cartSummary"><span>Subtotal <strong>{money(cart.reduce((s,p)=>s+p.price,0))}</strong></span><small>Shipping calculated at checkout</small><button className="primary">Proceed to checkout <ArrowRight/></button></div></>}</aside></div>}
  {authOpen&&<AuthModal onClose={()=>setAuthOpen(false)} onAuthenticated={u=>setUser(u)}/>}<div id="wishlist" className="wishlistAnchor"/>
 </main>
}
