import { useEffect, useMemo, useState } from 'react';
import { Heart, Search, ShoppingBag, Sparkles, ArrowRight, ChevronRight, Truck, RotateCcw, ShieldCheck, Users } from 'lucide-react';

type Product = { id:number; name:string; slug:string; description:string; price:number; rating:number; category:string; imageUrl:string };
const categories = ['T-Shirts','Hoodies','Jeans & Pants','Jackets','Sneakers','Caps & Hats','Bags','Sunglasses','Watches','Jewellery','Accessories'];
const fallback: Product[] = [
 {id:1,name:'Oversized Graphic Tee',slug:'oversized-graphic-tee',description:'Relaxed streetwear fit.',price:799,rating:4.8,category:'T-Shirts',imageUrl:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85'},
 {id:2,name:'Street Classic Sneakers',slug:'street-classic-sneakers',description:'Everyday street sneakers.',price:2499,rating:4.7,category:'Sneakers',imageUrl:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85'},
 {id:3,name:'Baggy Cargo Jeans',slug:'baggy-cargo-jeans',description:'Loose utility cargo silhouette.',price:1899,rating:4.6,category:'Jeans & Pants',imageUrl:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=700&q=85'},
 {id:4,name:'Minimal Hoodie',slug:'minimal-hoodie',description:'Clean heavyweight hoodie.',price:1699,rating:4.8,category:'Hoodies',imageUrl:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85'},
 {id:5,name:'NY Baseball Cap',slug:'ny-baseball-cap',description:'Classic everyday cap.',price:599,rating:4.5,category:'Caps & Hats',imageUrl:'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=700&q=85'},
 {id:6,name:'Aero Sunglasses',slug:'aero-sunglasses',description:'Minimal statement frames.',price:999,rating:4.6,category:'Sunglasses',imageUrl:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=700&q=85'}
];

export default function App(){
 const [products,setProducts]=useState<Product[]>(fallback); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [liked,setLiked]=useState<number[]>([]); const [cart,setCart]=useState<number[]>([]); const [chatOpen,setChatOpen]=useState(false);
 useEffect(()=>{ fetch((import.meta.env.VITE_API_URL||'http://localhost:8080')+'/api/v1/products').then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>{}); },[]);
 const visible=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(!query||`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[products,category,query]);
 const toggleLike=(id:number)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 return <main>
  <div className="topbar">🔥 Free shipping on orders over ₹999 <span/> New drops every week <span/> Student discount 10%</div>
  <header><div className="brand">NEXTGEN<small>WEAR WHAT'S NEXT</small></div><nav>{['Home','Shop','New Drops','Brands','Categories','Outfits','AI Stylist','Sale'].map(x=><a className={x==='Home'?'active':''} key={x}>{x}</a>)}</nav><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for clothes, sneakers, accessories..."/></div><button className="icon"><Heart/></button><button className="icon bag"><ShoppingBag/><b>{cart.length}</b></button><div className="avatar">N</div></header>
  <section className="hero"><div className="heroCopy"><p className="eyebrow">GEN Z FASHION DESTINATION</p><h1>Wear What's <em>Next.</em></h1><p>Trendy clothes. Iconic accessories. Personalized by AI. Because your style is more than just an outfit — it's your story.</p><div className="actions"><button className="dark">Shop New Drops <ArrowRight size={16}/></button><button className="outline" onClick={()=>setChatOpen(true)}>Try AI Stylist <Sparkles size={16}/></button></div><div className="trust"><span><Truck/>Free Shipping<small>on orders above ₹999</small></span><span><RotateCcw/>Easy Returns<small>7-day hassle free</small></span><span><ShieldCheck/>Secure Payments<small>100% safe & encrypted</small></span><span><Users/>50K+<small>Happy Customers</small></span></div></div><div className="heroPhoto"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1300&q=90"/><div className="scribble">Good outfits.<br/>Better days.</div></div><aside><div className="aiHead"><Sparkles/> <strong>Your AI Stylist</strong><i>BETA</i></div><p>Get outfit ideas, style suggestions and color matches — just for you.</p>{['Suggest a college outfit under ₹2000','What goes with my black cargos?','Show me Korean streetwear looks','What’s trending this week?'].map(q=><button key={q} onClick={()=>setChatOpen(true)}>{q}<ChevronRight size={14}/></button>)}<button className="purple" onClick={()=>setChatOpen(true)}>Start Chatting <ArrowRight size={15}/></button></aside></section>
  <section className="cats">{categories.map(c=><button key={c} onClick={()=>setCategory(c)}><div>{c.slice(0,1)}</div><span>{c}</span></button>)}<button onClick={()=>setCategory('All')}><div>→</div><span>View All</span></button></section>
  <section className="promos"><article><small>NEW DROP</small><h2>Urban<br/><i>Essentials</i></h2><button className="dark">Shop Now <ArrowRight size={14}/></button></article><article className="look"><div><h2>Complete<br/>The Look</h2><p>Outfit ideas, curated by AI for every occasion.</p><button className="outline">Explore Outfits <ArrowRight size={14}/></button></div><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=80"/></article><article className="sale"><small>GEN Z</small><h2>SALE</h2><p>Up to 50% Off</p><button className="dark">Shop Sale <ArrowRight size={14}/></button></article></section>
  <section className="productsSection"><div className="sectionTitle"><div><h2>Trending Now</h2><p>Most loved by our community</p></div><span>{visible.length} products</span></div><div className="filters"><button className={category==='All'?'selected':''} onClick={()=>setCategory('All')}>All</button>{['T-Shirts','Hoodies','Jeans & Pants','Sneakers','Accessories'].map(c=><button className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid">{visible.map(p=><article className="product" key={p.id}><div className="pimg"><img src={p.imageUrl} alt={p.name}/><button onClick={()=>toggleLike(p.id)}><Heart fill={liked.includes(p.id)?'currentColor':'none'}/></button></div><h3>{p.name}</h3><strong>₹{p.price.toLocaleString('en-IN')}</strong><span>★ {p.rating}</span><button className="add" onClick={()=>setCart(v=>[...v,p.id])}>Add to Cart</button></article>)}</div></section>
  <section className="aiStrip"><div><h2>Style Smarter with <em>AI</em></h2><p>Tell us your vibe, occasion and budget — get a complete look from the real NEXTGEN catalog.</p></div><button className="purple" onClick={()=>setChatOpen(true)}>Try AI Stylist <ArrowRight size={16}/></button></section>
  {chatOpen&&<div className="overlay" onClick={()=>setChatOpen(false)}><div className="chat" onClick={e=>e.stopPropagation()}><header><strong>✦ NEXTGEN AI Stylist</strong><button onClick={()=>setChatOpen(false)}>×</button></header><div className="bot">Tell me your vibe, occasion, size and budget. I'll help you build a look.</div><div className="quick"><button onClick={()=>setQuery('hoodie')}>College fit under ₹2000</button><button>Style my black cargos</button><button>Trending streetwear</button></div><div className="chatInput"><input placeholder="Describe your style..."/><button className="purple">→</button></div></div></div>}
 </main>
}
